services:
        api:
                build: ./app
                ports: ['5000:5000']
                volumes:
                        - ./app:/usr/src/app
                        - /usr/src/app/build
                        - /usr/src/app/node_modules
        nginx: 
                image: nginx:latest
                container_name: production_nginx
                volumes:
                        - ./nginx.conf:/etc/nginx/nginx.conf
                        - ./nginx/error.log:/etc/nginx/error_log.log
                        - ./nginx/cache/:/etc/nginx/cache
                        - /etc/letsencrypt/:/etc/letsencrypt/
                ports:
                        - 80:80
                        - 443:443