services:
        api:
                build: ./app
                ports: ['5000:5000']
                volumes:
                        - ./app:/usr/src/app
                        - /usr/src/app/build
                        - /usr/src/app/node_modules
                depends_on:
                        - "mongo"
        nginx: 
                image: nginx:latest
                container_name: production_nginx
                volumes:
                        - ./nginx/production.conf:/etc/nginx/nginx.conf
                        - ./nginx/error.log:/etc/nginx/error_log.log
                        - ./nginx/cache/:/etc/nginx/cache
                        - /etc/letsencrypt/:/etc/letsencrypt/
                        - app_bundle:/usr/share/nginx/html:ro
                ports:
                        - 80:80
                        - 443:443
                depends_on:
                        - "api"
                        - "client"
        client:
                build: ./client
                ports: ['3000:3000']
                volumes: 
                        - ./client:/usr/src/app
                        - app_bundle:/usr/src/app/build
                        - /usr/src/app/node_modules
                stdin_open: true
                environment:
                        - CHOKIDAR_USEPOLLING=true
                depends_on:
                        - "api"
        mongo:
                image: mongo
                ports:
                        - 27017:27017
                volumes:
                        - mongodb:/data/db
volumes:
        mongodb:
        app_bundle: