services:
  api:
    image: node:12-alpine
    ports:
      - 5000:5000
    volumes:
      - ./api:/app
    working_dir: /app
    env_file:
      - .env
    command: sh -c 'npm install && npm run dev'
  caddy:
    image: caddy:2.7.5-alpine
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    env_file:
      - .env
    ports:
      - 80:80
      - 443:443
  client:
    image: node:12-alpine
    volumes:
      - ./client:/app
    ports: 
      - 3000:3000
    env_file:
      - .env
    working_dir: /app
    entrypoint: ./entrypoint.sh
    stdin_open: true
  mongo:
    image: mongo
    volumes:
      - mongodb:/data/db
volumes:
  mongodb:
