name: Build, Transfer, and Deploy Billboard Docker Images

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and Save Docker Images
        run: ops/build.sh

      - name: Transfer Docker Images to Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_KEY }}
          source: "billboard-*.tar"
          target: "/tmp"

      - name: Load Docker Images on Server and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            docker load -i /tmp/billboard-web.tar
            docker load -i /tmp/billboard-api.tar
            docker load -i /tmp/billboard-db.tar
            cd /path/to/docker-compose
            docker-compose up -d
